### ISSUE TITLE
When upload many files, convert them into .zip

### ISSUE THREAD

**Issue by jwt1029** [jwt1029/NaverCloud#14]
When upload many files, convert them into .zip file.
It's more confortable to manage files.

Able to use this with `checkBox`.
- files -> `files`
- files -> `folder`
- files -> `.zip`

**Comment by AshtonYoon** [comment]
:)

**Comment by jwt1029** [comment]
`http://files.cloud.naver.com/MakeDirectory.ndrive`

[Request]
`userid`
`useridx`
`dstresource (/FolderName/)`

**Comment by jwt1029** [comment]
We though `.zip` is not useful.
Instead, support `make folder` operation.
